[package]
name = "surrealdb-query"
publish = false
edition.workspace = true
version.workspace = true
authors.workspace = true
description = "Workspace skeleton crate for the future query layer"
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
license-file.workspace = true

[features]
default = []
arbitrary = ["dep:arbitrary"]

[dependencies]
surrealdb-support = { workspace = true }
surrealdb-types = { workspace = true }
phf = { workspace = true, features = ["macros", "unicase"] }
unicase.workspace = true
arbitrary = { workspace = true, features = ["derive"], optional = true }

[lints]
workspace = true

[lib]
name = "surrealdb_query"
