[package]
name = "surrealdb-storage-indxdb"
publish = false
edition.workspace = true
version.workspace = true
authors.workspace = true
description = "Workspace skeleton crate for the future IndxDB storage backend"
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
license-file.workspace = true

[features]
default = []

[dependencies]

[lints]
workspace = true

[lib]
name = "surrealdb_storage_indxdb"
